### ISSUE TITLE
Get navigation menu to appear on multiple pages DEADLINE:

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#1]
Currently the "navigation menu" is hard-coded in the home.html template. It should show up on every page. (try the 'extends' or 'include' template tags)

**Comment by michaelplews** [comment]
I'm a bit confused. Sounds like I can do this easily with PHP, but that requires Apache. Could also use js. Or is it simply adding:

```
{% include "navigation.html" %}
```

?
