### ISSUE TITLE
Add a polyfill for a datepicker DEADLINE:

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#100]
Adding the jqueryui datepicker made the date picker return incorrect values. I removed the code for now.

I think we should let the browser implement [input=date] tags if it can since it's a part of HTML5. If you want to include a fallback for older browsers, it's better to use a polyfill through something like modernizr.

**Comment by mrplePurple** [comment]
Are you referring to the ULON generator? That's weird, I tested it thoroughly when implementing it.

**Comment by michaelplews** [comment]
Are you referring to the ULON generator? That's weird, I tested it thoroughly when implementing it.

(The right account this time)

**Comment by canismarko** [comment]
I ran into the bug on the add container form but it also happens on the
ULON generator. Try setting the date to Nov 30 2016. It just stays blank
and the console returns a warning that "jquery-1.12.4.js:8254 The
specified value "11/30/2016" does not conform to the required format,
"yyyy-MM-dd"." Tested with chromium 54.0.2840.71 (64-bit) on Arch Linux.

**Comment by canismarko** [comment]
Regardless, adding the jquery datepicker leaves us with two datepickers on one field: the native one and the jquery one, which seems like a bad idea.

**Comment by michaelplews** [comment]
OK I'll fix it

**Comment by canismarko** [comment]
Just FYI, I haven't pushed changes yet so the jquery line is still in there.

**Comment by michaelplews** [comment]
So if you remove it we actually need to do nothing? Seeing as you said there's already a datepicker there?

**Comment by canismarko** [comment]
There will be a datepicker in [browsers that implement the new HTML5 input tags](http://caniuse.com/#search=input%20date). Otherwise it will just be a text field. Modernizr is a js library that detects feature support and allows you to load a polyfill that mimics the built in functionality of compliant browsers.

**Comment by michaelplews** [comment]
OK I'll look into Modernizr then

**Comment by michaelplews** [comment]
Looks like [this](http://stackoverflow.com/questions/18020950/how-to-make-input-type-date-supported-on-all-browsers-any-alternatives) solves our problem. 

In this case, I can just throw in
```javascript
if ( $('[type="date"]').prop('type') != 'date' ) {
    $('[type="date"]').datepicker();
}
```
and use the jQuery date picker for anything that doesn't already have a builtin HTML5 datepicker. Right?
