### ISSUE TITLE
ULON generator raises 500 exception

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#114]
> Internal Server Error: /utilities/make_ulon/
> Traceback (most recent call last):
>   File "/srv/professor_oak_venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/srv/professor_oak_venv/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
>     return view_func(request, *args, **kwargs)
>   File "/srv/professor_oak_venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/srv/professor_oak_venv/lib/python3.5/site-packages/django/views/generic/base.py", line 89, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/srv/professor_oak_venv/lib/python3.5/site-packages/django/views/generic/edit.py", line 215, in post
>     return self.form_valid(form)
>   File "./oak_utilities/views.py", line 116, in form_valid
>     doc.generate_pdf()
>   File "/srv/professor_oak_venv/lib/python3.5/site-packages/pylatex/document.py", line 117, in generate_pdf
>     os.chdir(dest_dir)
> FileNotFoundError: [Errno 2] No such file or directory: './media_files//ULONs'
>

**Comment by michaelplews** [comment]
Already fixed and pushed to github
