### ISSUE TITLE
Post the latest XKCD somewhere on the site

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#22]
Turns out there's an XKCD python library: https://pypi.python.org/pypi/xkcd/2.3.1

Pretty sure this means we should include the latest XKCD somewhere, maybe on the inventory main page?

**Comment by michaelplews** [comment]
This sounds like something I could do!

**Comment by michaelplews** [comment]
Done! still needs to be properly placed with CSS but I'll open another issue for that.
