### ISSUE TITLE
Add field for characterization data (XRD, TGA, etc) DEADLINE:

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#32]

**Comment by michaelplews** [comment]
I retract my original comment about accepting certain file extensions. It would become infinitely more complex if someone the just changed the extension of a malicious file. Then we would have to match file headers etc. 

If we just run with uploading multiple file types, possibly with a maximum file size to avoid blowing up geodude? If there's nothing more complicated I'm missing, I could assign this to myself.

**Comment by canismarko** [comment]
a195e116eceab434837f4ff3678fe1b04f221eeb
