### ISSUE TITLE
Come up with a better domain name DEADLINE:

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#40]

**Comment by canismarko** [comment]
How about professoroak.chem.uic.edu?

**Comment by michaelplews** [comment]
That works. Unless we want something like 'cabanainventory.chem.uic.edu'. But either works for me.

**Comment by canismarko** [comment]
Or maybe cabanalab.chem.uic.edu? I feel cabanainventory would be outdate once we started adding in the lab automation stuffs.

**Comment by michaelplews** [comment]
Yeah I prefer that one actually.

**Comment by canismarko** [comment]
Request sent to Don Rippon.
