### ISSUE TITLE
Add a field for comments on each container DEADLINE:

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#42]

**Comment by michaelplews** [comment]
Are we envisioning this to be more of a 'comment thread' or is it going to be a comment box that people anonymously write in?

**Comment by canismarko** [comment]
I think the latter would be easier for now. If there's a need for threading, we can add it as a future goal?

**Comment by canismarko** [comment]
60f741235fddc6bb752e9081243f483b0faccdc4
