### ISSUE TITLE
Improvements to add container form and template

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#43]
Based on observations with Gene. We told him to "add a chemical you haven't seen before" and he skipped the chemical search panel. Should we disable it until the user has type text in to the search box?

**Comment by michaelplews** [comment]
Did we decide to disable the whole thing until he had at least tried? We might have to bite the bullet and make a function that searches for duplicates and shows a notification if a duplicate exists

**Comment by canismarko** [comment]
Let's leave it for now and make a decision once we see how people use it. Maybe it won't actually be a problem since we did tell Gene that it was a new chemical. I'm going to move this to future development.
