### ISSUE TITLE
Incorporate HttpRequest to send an email for someone waiting for a slot on the cycler

### ISSUE THREAD

**Issue by michaelplews** [canismarko/professor_oak#58]
Have geodude check a list when a httprequest is sent and email the first person on that list waiting for a VMP3 slot.

**Comment by michaelplews** [comment]
- Click 'Sign-up' Button
  - [ ] Adds a reference to the user object to a list 
  - [ ] Response (toaster)
- Receives an e-mail when a slot becomes available
  - [ ] Python script sends an HttpRequest to Geodude
  - [ ] Geodude responds by sending an email to the user specified and removes them from the list
- Allows the user to 'skip' their turn
  - [ ] Following the link in the email sends the same HttpRequest (landing page??)

**Comment by michaelplews** [comment]
If I want to store a list of users in the order they sign up in, would it be better to store a reference to the JSON object in a text file? or is there a better way?

**Comment by canismarko** [comment]
I'm not sure what you mean by "reference to the JSON object". Kind of depends on what data you need to store.

You might consider SQLite, it's basically a database but stored in a file on disk. It can't be written by a text editor, though. There's a python implementation in the standard library: https://docs.python.org/3.5/library/sqlite3.html

If you need it to be plain-text json would work fine. You could also use csv, which would make it easier to sort and rearrange the entries.

**Comment by michaelplews** [comment]
I mean't rather than keeping the email address in a text file, I could keep the pk of the user so I could access other things like user name, email etc. I'll look at csv. 

Hope you're enjoying the holidays!

**Comment by canismarko** [comment]
@michaelplews Mind if I close this one? We haven't had any problems with channel usage recently.

**Comment by michaelplews** [comment]
Yup, this turned out solved.
