### ISSUE TITLE
By popular demand, make the inventory a login-only service DEADLINE:

### ISSUE THREAD

**Issue by michaelplews** [canismarko/professor_oak#69]
I presume we want to do the entire site? Rather than just do the list of chemicals?

**Comment by canismarko** [comment]
Still not sure I see the benefit in doing this...

**Comment by michaelplews** [comment]
Me either, but if this is what the people want...

**Comment by canismarko** [comment]
The only person that actually said he was in favor of it was Ryan, and he didn't actually give a reason for it. You know exactly what this link is going to be before clicking on it...
http://imgur.com/gallery/X17puIB

(you'll still click on it anyway, though)

**Comment by michaelplews** [comment]
Sam was the one who brought it up in the email, but you're right I can't see it changing anything really. Notice no one has any feedback for my 'what about undergrads' point.

**Comment by canismarko** [comment]
We will need this anyway if it ever expands to a second research group so that a user only see her group's chemicals.

We'll need a new auth group for Miranda and Randy with maybe read-only access?

**Comment by michaelplews** [comment]
I'm not sure if this is still happening but for the time being should we defer to the Future Development milestone?

**Comment by canismarko** [comment]
Honestly, Ryan was the one who wanted this more than anyone so I'm just going to close it until someone brings it up again.
