### ISSUE TITLE
Create a form for adding a new chemical

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#7]

**Comment by michaelplews** [comment]
If possible, it would be nice to combine this and the previous issue. That was one of the complaints gene had; that there were too many places to enter data. 

One page for entering a new chemical and it's container and populating the 'chemical information' part of it if it already exists. Think that could work?

**Comment by canismarko** [comment]
Yeah that's pretty much what I was thinking too. Maybe a text box, user types in the name of the chemical and if it's not already in the database then the form has some extra fields for CAS, NFPA etc.

I think we'll still need two separate Form classes, though, from Django's point of view.

**Comment by michaelplews** [comment]
Ah I see. Cool. I'm not good at thinking about things from the point of view of the backend

**Comment by michaelplews** [comment]
That's what she said
