### ISSUE TITLE
Search by container ID number

### ISSUE THREAD

**Issue by michaelplews** [canismarko/professor_oak#74]
Over the past few days I've found myself lneeding to look up a container based on its barcode ID number. I can do this relatively easily through the admin console, but the average user won't be able to.

My idea is to have a search box somewhere (homepage? two buttons for one box (currently the mark as empty box) ) and have django lookup the container ID and return the chemical detail page with the container matching the ID number highlighted with the alert class

**Comment by canismarko** [comment]
Yeah that sounds like a good idea. I would push back against the idea of
having on the homepage, though, since it's probably not going to be used
very often.

**Comment by michaelplews** [comment]
Why don't we change the 'mark as empty' field on the homepage to 'search by ID number', seeing as we will soon have the scanner PiNode. The only extra step for the user would be to click'mark as empty'

Thoughts?

**Comment by canismarko** [comment]
I like it.

**Comment by michaelplews** [comment]
Done.
