### ISSUE TITLE
Add "available-to-all" field to container class?

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#78]
Stanford's inventory has a field that indicates if the container is free for others to use as needed or if you should ask the owner first. Might be a good idea?

**Comment by michaelplews** [comment]
Good idea, maybe not within the group perhaps as I think all chemicals are free for others to use within our group but definitely a necessity if we open it up to cross group chemical viewing

**Comment by canismarko** [comment]
Hasn't been an problem in our group, so I'm just closing this.
